on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - name: setup-and-module
      run: |
        type NUL > module.tar.gz
    - name: upload-module
      uses: actions/upload-artifact@v4
      with:
        name: module
        path: ./module.tar.gz
