name: Run linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Lint and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make setup

      - name: Run lint
        run: make lint

      - name: Build
        run: make tflite_cpu
